In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/AmanChn/Dataset/main/Womens%20Clothing%20E-Commerce%20Reviews.csv')

In [3]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                              Review  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Unnamed: 0         23486 non-null  int64 
 1   Clothing ID        23486 non-null  int64 
 2   Age                23486 non-null  int64 
 3   Title              19676 non-null  object
 4   Review             22641 non-null  object
 5   Rating             23486 non-null  int64 
 6   Recommended IND    23486 non-null  int64 
 7   Positive Feedback  23486 non-null  int64 
 8   Division           23472 non-null  object
 9   Department         23472 non-null  object
 10  Category           23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [5]:
df.shape

(23486, 11)

In [6]:
# MISSING VALUES

In [7]:
df.isna().sum()

Unnamed: 0              0
Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended IND         0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [8]:
df[df['Review']==""]=np.NaN

In [9]:
df['Review'].fillna("No Review", inplace=True)

In [10]:
df.isna().sum()

Unnamed: 0              0
Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended IND         0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [11]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [12]:
# DEFINE LABEL y and featuerea x

In [13]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review', 'Rating',
       'Recommended IND', 'Positive Feedback', 'Division', 'Department',
       'Category'],
      dtype='object')

In [14]:
X=df['Review']

In [15]:
y = df['Rating']

In [16]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [17]:
X.shape

(23486,)

In [18]:
y.shape

(23486,)

In [19]:
X

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [20]:
y

0        4.0
1        5.0
2        3.0
3        5.0
4        5.0
        ... 
23481    5.0
23482    3.0
23483    3.0
23484    3.0
23485    5.0
Name: Rating, Length: 23486, dtype: float64

In [21]:
# Get train test split

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, stratify = y ,random_state=12529)

In [24]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [25]:
# Get feature text Conversion to tokens

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
cv = CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2,3), stop_words = 'english', max_features=5000  )

In [28]:
X_train = cv.fit_transform(X_train)

In [29]:
cv.get_feature_names_out()

array(['0p fit', '10 10', '10 12', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [30]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [31]:
X_test = cv.fit_transform(X_test)

In [32]:
cv.get_feature_names_out()

array(['10 12', '10 fit', '10 got', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [33]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [34]:
#GET MODEL

In [35]:
from sklearn.naive_bayes import MultinomialNB

In [36]:
model = MultinomialNB()

In [37]:
model.fit( X_train,y_train )

MultinomialNB()

In [38]:
# GET MODEL PREDICTION

In [39]:
y_pred = model.predict(X_test)

In [40]:
y_pred.shape

(7046,)

In [41]:
y_pred

array([5., 1., 5., ..., 3., 4., 4.])

In [42]:
# GET Probability of Each Predicted CLass

In [43]:
model.predict_proba(X_test)

array([[0.05195875, 0.08260154, 0.17570434, 0.22106802, 0.46866734],
       [0.36050981, 0.05009674, 0.11403525, 0.15638324, 0.31897497],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.05656578, 0.02108659, 0.48254844, 0.02343763, 0.41636156],
       [0.01070241, 0.00656414, 0.00939201, 0.92843325, 0.04490819],
       [0.03736085, 0.04541674, 0.05181356, 0.4371705 , 0.42823834]])

In [44]:
#GET MODEL EVALUATION

In [45]:
from sklearn.metrics import confusion_matrix, classification_report

In [46]:
confusion_matrix( y_test, y_pred )

array([[  18,   28,   29,   48,  130],
       [  60,   40,   46,  102,  222],
       [ 101,   86,  100,  185,  389],
       [ 191,  161,  166,  321,  684],
       [ 421,  401,  355,  788, 1974]])

In [47]:
print(classification_report( y_test, y_pred ))

              precision    recall  f1-score   support

         1.0       0.02      0.07      0.03       253
         2.0       0.06      0.09      0.07       470
         3.0       0.14      0.12      0.13       861
         4.0       0.22      0.21      0.22      1523
         5.0       0.58      0.50      0.54      3939

    accuracy                           0.35      7046
   macro avg       0.21      0.20      0.20      7046
weighted avg       0.39      0.35      0.37      7046



In [48]:
#recategories Ratings as poor(0) and Good(0) 

In [49]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [50]:
# Re-Rating as 1,2,3 as 0 and 4,5 as 1

In [51]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}}, inplace=True)

In [52]:
y = df['Rating']

In [53]:
X = df['Review']

In [54]:
# TRAIN TEST SPLIT

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, stratify = y ,random_state=12529)

In [57]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

In [58]:
# Get feature text Conversion to tokens

In [59]:
from sklearn.feature_extraction.text import CountVectorizer

In [60]:
cv = CountVectorizer(lowercase = True, analyzer='word', ngram_range=(2,3), stop_words = 'english', max_features=5000  )

In [61]:
X_train = cv.fit_transform(X_train)

In [62]:
X_test = cv.fit_transform(X_test)

In [63]:
# GET MODEL RE-TRAIN

In [64]:
from sklearn.naive_bayes import MultinomialNB

In [65]:
model = MultinomialNB()

In [66]:
model.fit( X_train,y_train )

MultinomialNB()

In [67]:
# GET MODEL PREDICTION

In [68]:
y_pred = model.predict(X_test)

In [69]:
y_pred.shape

(7046,)

In [70]:
y_pred

array([1., 1., 1., ..., 1., 1., 0.])

In [71]:
# GET MODEL EVALUATION

In [72]:
from sklearn.metrics import confusion_matrix, classification_report

In [73]:
confusion_matrix( y_test, y_pred )

array([[ 326, 1257],
       [1038, 4425]])

In [74]:
print(classification_report( y_test, y_pred ))

              precision    recall  f1-score   support

         0.0       0.24      0.21      0.22      1583
         1.0       0.78      0.81      0.79      5463

    accuracy                           0.67      7046
   macro avg       0.51      0.51      0.51      7046
weighted avg       0.66      0.67      0.67      7046

